# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Match_Detail',
            fields=[
                ('match_detail_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('team1_score', models.CharField(max_length=50)),
                ('team2_score', models.CharField(max_length=50)),
                ('team1_overs', models.CharField(max_length=50)),
                ('team2_overs', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('runs', models.DecimalField(decimal_places=0, max_digits=5)),
                ('wickets', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statistics_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('played', models.DecimalField(decimal_places=0, max_digits=5)),
                ('won', models.DecimalField(decimal_places=0, max_digits=5)),
                ('lost', models.DecimalField(decimal_places=0, max_digits=5)),
                ('tied', models.DecimalField(decimal_places=0, max_digits=5)),
                ('points', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('captain', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='main_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='main_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Venue'),
        ),
    ]
