# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_detail',
            name='match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_overs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_overs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Match_Detail',
        ),
    ]
