# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20161130_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.ImageField(default='default.png', upload_to='/media/'),
        ),
    ]
