# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20161130_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_url',
            field=models.ImageField(default='default.png', upload_to='/media/'),
        ),
        migrations.AddField(
            model_name='team',
            name='profile_url',
            field=models.ImageField(default='default.png', upload_to='/media/'),
        ),
    ]
