# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_enquiries_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='date',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='time',
        ),
    ]
