# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20161207_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
